### PR TITLE
Allow Latch to work with latest Joomla version

### PR DESCRIPTION
**Pull request by phproberto**
This: 
- Fixes the package manifest that didn't allow to upgrade Latch
- Uses the SDK directly from composer to ensure that it can be upgraded easily when we want just running `compose update`. This also fixes issue because currently Latch is using a class named Error without any namespace and it conflicts because that's a very generic name. I have included the SDK files in the repository so download ZIP and install works as expected but ideally we should remove those files and only include them in the releases section that is now unused ( https://github.com/ElevenPaths/latch-plugin-joomla/releases ).
- Ensures that it works with latest development Joomla version (See issue https://github.com/ElevenPaths/latch-plugin-joomla/issues/14 )
- Moves the library classes (not part of the SDK) to start using namespace `ElevenPaths\Latch\Joomla` so we can add there anything needed with nowadays php code.

Also some notes about this repository & global latch management:
- When you search for Latch in packagist ( https://packagist.org/search/?q=latch ) there is a result but it's not the official SDK but a fork of it ( https://packagist.org/packages/elevenpaths/latch-sdk-php ) which is not updated. I think you should claim ownership of that package so anybody can use the packagist version. I was forced to add the repository directly to integrate it. 
- Latch is opensource so we can integrate update servers here. That way the Latch joomla plugin can be upgraded automatically directly from Joomla and site administrators will be notified about new versions.
- You should start creating git tags for versions so people can know what's happening here and can use packagist without issues. This applies to both PHP SDK and this repository. 
- Joomla 2.5 support has been finished. We could release a new major version and use the latest Joomla 3.x features to use AJAX to pair account, etc.
- I've contributed this because a friend asked me but I stopped using Latch because the lack of support, missing composer package, etc. I can help you to maintain this repository properly if you need it. I love the Latch concept and I recommended it to a lot of Joomla friends and it's a shame its current state. So if you need help just ping me!

### CODE REVIEW

**Comment by jaesga** [comment]
Hi Roberto,

Thank you so much for your contribution to this project. 
We are going to review and test your pull request as soon as possible and if everything is fine we will merge it.

Regards,
Javi.

**Comment by phproberto** [comment]
Thanks Javi

**Comment by jaesga** [comment]
> So if you need help just ping me!

Roberto, could you write me an email to javi /at/ 11paths /dot/ com to have your contact please?

**Comment by phproberto** [comment]
I sent you an email yesterday @jaesga

**Comment by phproberto** [comment]
Any news about this? +1 month waiting now.

**Comment by jaesga** [comment]
Hi, 

Sorry for the delay with this PR. Initially we had to deprioritize this task in order to maintain our roadmap but I have recap with our QA team and and they are going to test it these days. 

I have also pending a little catchup with you by email regarding this repo, etc.

Sorry for the inconvenience and thank you for your patience. 
Regards,
Javi

**Comment by phproberto** [comment]
I have updated the PR with some changes:
* Now we don't track composer libraries
* Moved all the extensions to an `extensions` folder. 
* Language files are now loaded from each extension folder instead of using the global language folder.
* Integrated a Gulp build system that:
    * Releases current version with `gulp release`
    * Includes integration with [Browsersync](https://browsersync.io/) to ease development
    * Watches for changes in the extensions and instantly updates browser. That covers css, php & language files.

Pending:
* [ ] Create package installer to perform common actions that now are done in modules & plugins like enabling/publishing them after install.
* [ ] Clean old language files to ensure that extensions files are used instead of global ones.
* [ ] Create update server section in manifest to automatically notify available updates.
* [ ] Update documentation.

**Comment by phproberto** [comment]
Gulp integration in action:

latch-gulp

**Comment by phproberto** [comment]
Now everything should be ok except documentation. Relevant changes:
* We have an [udpates](https://github.com/phproberto/latch-plugin-joomla/tree/update/updates) folder that will feed the server update check. I will provide the first update after this version is released. Now there is a `pkg_latch.xml` file but is empty.
* I've changed version to v3.0.0 because we will break B/C with old 2.5 sites.
* I've updated all the copyrights to 2016.
* Fixed a bug that prevented user plugin from being upgraded.
* We can now include small update scripts for each version just adding a file in this folder:
https://github.com/phproberto/latch-plugin-joomla/tree/update/extensions/updates 
That makes things easy to maintain. 

I will write docs for the processes required to maintain the repository with the new structure & tools after we merge this.

I won't merge it until I get feedback or a week passes. So @jaesga any feedback is appreciated.

For reference this is a sample update served by the repository for a v3.0.0 version:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<updates>
	<update>
		<name>Latch for Joomla!</name>
		<description>Joomla! extension to integrate with Latch.</description>
		<element>pkg_latch</element>
		<type>package</type>
		<client>0</client>
		<client_id>0</client_id>
		<version>3.0.0</version>
		<infourl title="Latch 3.0.0 released">https://github.com/ElevenPaths/latch-plugin-joomla/releases/tag/v3.0.0</infourl>
		<downloads>
			<downloadurl type="full" format="zip">https://github.com/ElevenPaths/latch-plugin-joomla/releases/download/v3.0.0/latch-plugin-joomla-v3.0.0.zip</downloadurl>
		</downloads>
		<maintainer>Eleven Paths</maintainer>
		<maintainerurl>https://www.elevenpaths.com</maintainerurl>
		<targetplatform name="joomla" version="3"/>
	</update>
</updates>
```

**Comment by jaesga** [comment]
Code looks good to me. I will trigger our QA process once we have release uploaded so it won't be a bottleneck like the previous version of the PR.


Thank you so much Roberto for your great work.
Regards,
Javi.

**Pull request merged**
